apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-08-09T21:50:12Z"
  generation: 2
  labels:
    app: cambio-service
  name: cambio-service
  namespace: default
  resourceVersion: "59095"
  uid: 1b6ce677-f63b-45dd-9a79-25157b1f1347
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cambio-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cambio-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://192.168.15.7:3306/cambio_service
        image: dubacchiega/cambio-service:kube-v1
        imagePullPolicy: IfNotPresent
        name: cambio-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-08-09T21:50:12Z"
    lastUpdateTime: "2025-08-09T21:50:22Z"
    message: ReplicaSet "cambio-service-6d9b8bb458" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-08-11T15:02:34Z"
    lastUpdateTime: "2025-08-11T15:02:34Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-08-09T21:50:32Z"
  labels:
    app: cambio-service
  name: cambio-service
  namespace: default
  resourceVersion: "57196"
  uid: ed4d38cc-5cce-4fe0-9591-a949ed29311e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.128.200
  clusterIPs:
    - 10.103.128.200
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31646
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: cambio-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}