apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: cambio-service
  name: cambio-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cambio-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cambio-service
    spec:
      containers:
      - name: cambio-service
        image: dubacchiega/cambio-service:kube-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://192.168.15.7:3306/cambio_service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cambio-service
  name: cambio-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31646
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: cambio-service
  sessionAffinity: None
  type: LoadBalancer
