apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: book-service
  name: book-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: dubacchiega/book-service:kube-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://10.30.30.12:3306/book_service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-service
  name: book-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30266
      port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: book-service
  sessionAffinity: None
  type: LoadBalancer
