name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
        - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt' # See 'Supported distributions' for available options
#
#    - name: Build Eureka Naming Server Docker Image
#      working-directory: ./naming-server
#      run: mvn spring-boot:build-image -DskipTests
#
#    - name:  Build API Gateway Docker Image
#      working-directory: ./api-gateway
#      run: mvn spring-boot:build-image -DskipTests

    - name: Build Cambio Service Docker Image
      working-directory: ./cambio-service
      run: mvn clean package -DskipTests

    - name: Build Book Service Docker Image
      working-directory: ./book-service
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      run: docker compose build

    - name: Tag Docker Images
      run: |
        docker tag ${{secrets.DOCKER_USERNAME}}/cambio-service:latest ${{secrets.DOCKER_USERNAME}}/cambio-service:${{github.RUN_ID}}
        docker tag ${{secrets.DOCKER_USERNAME}}/cambio-service:latest ${{secrets.DOCKER_USERNAME}}/cambio-service:kube-v1
        docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
        docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:kube-v1
        
        

    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/cambio-service:latest
        docker push ${{secrets.DOCKER_USERNAME}}/cambio-service:kube-v1
        docker push ${{secrets.DOCKER_USERNAME}}/cambio-service:${{github.RUN_ID}}
        docker push ${{secrets.DOCKER_USERNAME}}/book-service:latest
        docker push ${{secrets.DOCKER_USERNAME}}/book-service:kube-v1
        docker push ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
